# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  twitter_consumer_key: duf8jf9s1BmJ3Jw84OpEK06Iu
  twitter_consumer_key_secret: aYrs1UihxSLQdsobFio8JITRUffcntlDkuYAmzNax9h2bROn4z
  fb_app_id: 935324769825251
  fb_app_secret: 9b278b47dc8122f736a854d4cc94cf63
  foursquare_client_id: ZOT0IJWIC2SSWZFGIJKVOS423IA2NVE2AJZJKVQG2PSEBJXU
  foursquare_client_secret: ESLGHW0NAJRBH5QZQOKBR5AVPWFP24AKC23GASBP3OURF2LL
  s3_access_key_id: AKIAIEBRTBBZSOFDWDLQ
  s3_secret_access_key: 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
  instagram_client_id: 4365af21fe844413b26de35349e92a33
  instagram_client_secret: df699b4eb9734f2495d4da9823dc7bff
  google_api_key: AIzaSyCLdIAuLGrvIMhF_DDjof_39C3aDxCxh7E

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  domain_name: example.com
  secret_key_base: 02e3577f5ca4a4f85091b688b8b433a090e0ac19a73e02bf644443675045fcdfedc8b1d45cab481556e569ef7881210986aa52bcf6ca89bd8252dbae97e54265
  s3_bucket: foodfave-development

  <<: *default

test:
  domain_name: example.com
  secret_key_base: 13bb2d3dc1ed1c99b0d80cc0bf4ced0b385134b23a7556862b197308abc02c420840d368b4274570170f4e1c94f88b450cae2ddf02c0e610da235af5b7a415ed
  s3_bucket: foodfave-test
  s3_access_key_id: AKIAIEBRTBBZSOFDWDLQ
  s3_secret_access_key: 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

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: foodf-staging.herokuapp.com
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket: foodfave-production
  <<: *default
